# Generated by Django 2.0 on 2020-03-11 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DinnerTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='数据创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='数据修改时间')),
                ('tableName', models.CharField(max_length=25, verbose_name='餐桌名称')),
                ('tableKey', models.IntegerField(default=None, unique=True, verbose_name='餐桌代号')),
                ('status', models.SmallIntegerField(choices=[(1, '有人'), (2, '空闲')], default=2, verbose_name='餐桌状态')),
            ],
            options={
                'verbose_name': '餐桌信息',
                'verbose_name_plural': '餐桌信息',
                'db_table': 'tb_dinner_table',
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='数据创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='数据修改时间')),
                ('count', models.IntegerField(default=1, verbose_name='数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('evaluate', models.TextField(default='', verbose_name='评价信息')),
                ('score', models.SmallIntegerField(choices=[(0, '0分'), (1, '20分'), (2, '40分'), (3, '60分'), (4, '80分'), (5, '100分')], default=5, verbose_name='满意度评分')),
                ('is_commented', models.BooleanField(default=False, verbose_name='是否评价了')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_foods', to='foods.Foods', verbose_name='订单商品')),
            ],
            options={
                'verbose_name': '订单商品',
                'verbose_name_plural': '订单商品',
                'db_table': 'tb_order_goods',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='数据创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='数据修改时间')),
                ('order_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='订单号')),
                ('total_count', models.IntegerField(default=1, verbose_name='商品总数')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品总金额')),
                ('pay_method', models.SmallIntegerField(choices=[(1, '微信'), (2, '支付宝')], default=1, verbose_name='支付方式')),
                ('status', models.SmallIntegerField(choices=[(1, '待支付'), (2, '待评价'), (3, '已完成'), (4, '已取消')], default=1, verbose_name='订单状态')),
                ('comment', models.CharField(default=None, max_length=1024, verbose_name='订单备注')),
                ('tableKey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.DinnerTable', verbose_name='餐桌代号')),
            ],
            options={
                'verbose_name': '订单基本信息',
                'verbose_name_plural': '订单基本信息',
                'db_table': 'tb_order_info',
            },
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_goods', to='orders.OrderInfo', verbose_name='订单'),
        ),
    ]
