# Generated by Django 2.0 on 2020-03-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '可编辑'), (2, '正在备菜'), (3, '待支付'), (4, '已完成'), (5, '取消')], default=1, verbose_name='订单状态'),
        ),
    ]
